### ISSUE TITLE
Shared interfaces are incorrectly exploded against multiple subgraphs

### ISSUE THREAD

**Issue by nicholashagen** [apollographql/federation#1219]
In our particular team we use interfaces to allow a given layout engine to return various types of content/tiles from various subgraphs.   When using version `0.20.0`, everything works properly.  However, when trying to upgrade to 0.40+ (possibly before), it fails due to exploding the interfaces out.  This ends up sending fragment types to services that do no understand the particular implementation because Federation purely explodes all implementations regardless of what the service supports.

For example, consider the following schemas:

*global.graphqls*
```
interface Tile {
	id : ID!	
}
```

*news.graphqls*
```
interface Tile @extends {
	id : ID! @external
}

type ArticleTile implements Tile @key(fields: "id") {
	id : ID!
	title : String!
	body : String
}

extend type Query {
	newsTiles : [ Tile ]
}
```

*video.graphqls*
```
interface Tile @extends {
	id : ID! @external
}

type VideoTile implements Tile @key(fields: "id") {
	id : ID!
	title : String!
	url : String
}

extend type Query {
	videoTiles : [ Tile ]
}
```

*layout.graphqls*
```
interface Tile @extends @key(fields: "id") {
	id : ID! @external
}

type Layout {
	tiles : [ Tile ]
}

extend type Query {
	layout : Layout
}
```

If I make the query:
```
query {
  layout {
    tiles { id }
  }
}
```

It tries to federate a request to layout with:
```
{layout{tiles{__typename ...on ArticleTile{__typename id}...on VideoTile{__typename id}}}}
```

Technically speaking, Layout would actually support both of those tiles and can provide 
```
type ArticleTile @extends @key(fields: "id") {
   id : ID! @external
}
type VideoTile @extends @key(fields: "id") {
   id : ID! @external
}
```

This would fix the issue.  However, if we then decide to add a new search service and a SearchTile, it would again break layout until Layout is updated creating a dependency where both services must update and know about everything.

Would it make sense that when exploding it only explodes implementations that the specific service supports.  So, in the case about rather than sending ArticleTile, VideoTile, SearchTIle, it would realize search only has implementations specified for Article and VideoTile and thus only send those explosions.

That being said, I'm not sure why the explosions are needed in these cases.  In looking at the code in Apollo, there is a code block that in 0.20 was not triggered, but in newer version it is, cause the types are auto-added with `@join__` directives.  Specifically in `buildQueryPlan.ts` within `splitFields` there is
```
                const possibleFieldDefs = scope.possibleRuntimeTypes().map(runtimeType => context.getFieldDef(runtimeType, field.fieldNode));
                const hasNoExtendingFieldDefs = !possibleFieldDefs.some((field) => { var _a; return (_a = (0, composedSchema_1.getFederationMetadataForField)(field)) === null || _a === void 0 ? void 0 : _a.graphName; });
                if (hasNoExtendingFieldDefs) {

```

With those new directives in play the `hasNo` returns false bypassing that block.  In 0.20, that was `true` since it didn't have those custom directives added.

Similar, if the `newsTiles` specific function is used, it sends the entire implementations to the news service even though it only knows about two.  The fix here is to have an intermediate interface `NewsTile` and have each of its implementations implement both `Tile` and `NewsTile` and then have `newsTiles : [ NewsTile ]`.  That tends to work for the most part.

Ultimately, any service that wants to return an interface will not be extensible since it must know about the entire ecosystem of types which counteracts interfaces.

We are still playing with work arounds such as a `LayoutTile` that all owners may selectively implement to keep the layout types locked, but that puts a bi-directional access pattern on all the schemas since everything must know about layout and layout must know about everything to actually set the proper `__typename`.

**Comment by HaroldH76** [comment]
We also have this issue and are about to go live with our application. 
Is there any update about the status of this issue?

**Comment by HaroldH76** [comment]
Seems that this PR might be fixing this issue?
https://github.com/apollographql/federation/pull/864

**Comment by pcmanus** [comment]
There is imo 2 different things here.

The first is the fact that the query planner generates invalid queries due to "exploding" interfaces into all implementations even when querying services that don't know of some of those implementations. That issue is a bug and should indeed be (at least partly) fixed by #864 (and federation 2 both avoid this problem but is also a tad more efficient by avoiding such type explosion in a number of cases).

That said, even with that fixed, the 2nd thing is that the kind of usage pattern the description suggests is not really support by federation at the moment.

That is, my understanding of the example in the description is that it is trying to have a `layout` subgraph that defines and use the `Tile` interface with no implementations whatsoever and then various "implementations" subgraphs that provide concrete implementations for that `Tile` interface. But there is a few problem to make this work:
1. how do you implement the `layout` service in the first place? That is, you cannot implement a resolver for the `Layout.tiles` operation if no implementation are defined in the service. Concretely, Returning an object for an interface is not valid graphQL.
2. even if the first point was not an issue, how would the gateway know how to dispatch calls to the proper implementation services when it gets a `Tile.id` from the `layout` service? That is, having just an `id` gives you no information on the the concrete `Tile` implementaiton. Is it a video, a news, something else? I guess the gateway could query _all_ the implementation services in parallel and see which one answers, but but that's not very efficient and doesn't scale too well as you add new Tile implementations.

So what I'm trying to say is that the pattern of one subgraph declaring an interface, and then "dispatching" to multiple subgraphs, each providing one implementation of that interface, is not something federation really can achieve at the moment.

Which is *not* to say that it wouldn't be neat to have. I do think it would be great to solve that use case and I've started to think about this. But fwiw, I don't think it's a small thing to add/solve at all.

**Comment by nicholashagen** [comment]
For clarity, the layout service reads data from a data source which defines the actual tile types.  So, when the query is made to `layout` subgraph, it might respond with:
```
{
"data" : {
    "layout": {
        "tiles": [
            { "id" : "foo", "__typename" : "VideoTile" },
            { "id" : "bar", "__typename" : "ArticleTile" }
        ]
    }
}
```
So it doesn't know what the tiles are other than the types.  The gateway then uses that to expand the entity lookups to each of the service.  

So it'd hit the `video` graph with an entity query for `__typename: "VideoTile"` and `id : "foo"` and it'd hit article service in same fashion but for article type.

This works as expected.  The problem is that it hits each graph with both types but video does not know about article and thus it fails.

I will pull down the latest builds with that PR and see how that functions.  

Thanks.

**Comment by borispetelj-omega** [comment]
We still have the issue with updated library ("version": "0.33.9"). @pcmanus what do you mean by partially fixed in previous post?

"That issue is a bug and should indeed be (at least partly) fixed by #864"
