### ISSUE TITLE
error[E029]: Something went wrong! No build errors were recorded, but we also build a valid supergraph SDL.

### ISSUE THREAD

**Issue by basaa** [apollographql/federation#1346]
Hello guys,

I implemented a new project with Neo4j/GraphQL and Apollo Federation 2, subgraph services work fine but when I try to compose a supergraph I get this error:

error[E029]: Something went wrong! No build errors were recorded, but we also build a valid supergraph SDL.

My environment is :
- MacOS Big Sur
- @apollo/federation: "^2.0.0-alpha.1"
- @apollo/gateway: "^2.0.0-alpha.2"
- @apollo/subgraph: "^2.0.0-alpha.2"
- apollo-server: "^3.5.0"
- @neo4j/graphql: "^2.5.3"

Is there somebody who managed to make Neo4j/GraphQL + Fed2 work? Any suggestions would be very appreciated.

Thanks in advance

**Comment by pcmanus** [comment]
Hi @basaa. Could you give a little bit more details on what method you are using "to compose a supergraph"? In particular, I'm not sure where that `error[E029]: Something went wrong! No build errors were recorded, but we also build a valid supergraph SDL` comes from, but as far as I can tell, it doesn't come from the federation codebase.

That is, federation 2 is still in alpha and I'm sure the issue is ours, but I'm not sure where to start from here.

**Comment by basaa** [comment]
@pcmanus My issue was to make Neo4j/GraphQL and Apollo Federation directives coexist in a microservices architecture, I was trying to use `rover fed2 supergraph compose` but I had an error about duplication of the augmentedSchema directives and more, which is normal since all my subgraphs would produce those directives. Maybe my approach on trying to make those two framework working together was wrong; but at the end I made it work using `service listing` instead of `supergraph`.

I'll give a try to `rover fed2 supergraph compose` later on, since I believe that the gain in performance and more are very good.

Thank you for your time.

**Comment by abernix** [comment]
@basaa We've improved some of the messaging around this recently, but I can't guarantee this is solved for you.  I'm going to close this because there's not a reproduction I can quickly retry it on, but if you're able to try again and report back your experience, that'd be greatly appreciated.  If you do continue to encounter problems, please do report back with a minimal set of reproduction steps we can look at.

Thanks again for opening this originally!

**Comment by jord1e** [comment]
> @basaa We've improved some of the messaging around this recently, but I can't guarantee this is solved for you. I'm going to close this because there's not a reproduction I can quickly retry it on, but if you're able to try again and report back your experience, that'd be greatly appreciated. If you do continue to encounter problems, please do report back with a minimal set of reproduction steps we can look at.
> 
> Thanks again for opening this originally!

Hey, i just stumbled upon this non-descriptive error message when interfaces implement interfaces:
```
interface Node {
    id: ID!
}

interface NamedNode implements Node {
    id: ID!
}

type A implements NamedNode & Node {
    id: ID!
}

type Query {
    a: NamedNode!
}
```
reproduces this vague error when running `rover supergraph compose`:
![afbeelding](https://user-images.githubusercontent.com/30464310/155416207-bca40107-4684-4bbc-958b-c20549511a86.png)

May be related to apollographql/federation#227

**Comment by iyosayi** [comment]
I am also encountering this issue currently, I tried to compose my subgraphs and I got some composition errors which I fixed. After that, this same exact error is being returned and I don't know what to do currently, is there any pointers on how to resolve this. 

*Note:* I am using `@apollo/gateway 2-alpha` so I compose my schemas using `rover fed2 supergraph compose`. But this error still persists
